name: "Terraform Lambda"

on:
  push: 
    branches: 
      - main

jobs:
  terraform: 
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECREY_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - name: Check Out
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform Files
        run: terraform fmt -check

      - name: Validate Terraform Files
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan -input=false

      - name: Apply Terraform
        run: terraform apply -auto-approve
      
    
    
